### ISSUE TITLE
"Could not update contract values: request returned no valid JSON"

### ISSUE THREAD

**Issue by cpvbruno** [barisdemirdelen/homeassistant-greenchoice#2]
Logger: custom_components.greenchoice.api
Source: custom_components/greenchoice/api.py:148 
Integration: greenchoice ([documentation](https://github.com/barisdemirdelen/homeassistant-greenchoice/), [issues](https://github.com/barisdemirdelen/homeassistant-greenchoice/issues)) 
First occurred: December 25, 2022 at 1:50:49 PM (130 occurrences) 
Last logged: 11:21:24 PM

Could not update contract values: request returned no valid JSON

**Comment by ggian311** [comment]
Getting exactly the same error. Did you manage to find a fix by any chance?

**Comment by cpvbruno** [comment]
Nope, I quit and bought this device that can connect directly to home assistant: 

https://www.homewizard.com/nl/shop/wi-fi-p1-meter/

**Comment by ggian311** [comment]
Thanks for sharing @cpvbruno !

**Comment by struikc** [comment]
> Nope, I quit and bought this device that can connect directly to home assistant:
> 
> https://www.homewizard.com/nl/shop/wi-fi-p1-meter/

That doesn't really resolve the pricing issue, The P1-meter doesn't collect prices, other than filling it in yourself in de HomeWizard app (at least in my case). For the most, I agree as it comes to the usage of gas and electicity.

**Comment by cpvbruno** [comment]
Indeed you are right, if you find a solution please let me know

**Comment by johan-de-jong** [comment]
Maybe this is related? My logging shows similar events.

My appartement only has an electricty-, but no gas connection. Therefor the API seems to return a non-numeric value for sensor.meterstanden_gas_consumption and sensor.meterstanden_gas_price which produces the errors below.


```
Could not update contract values: request returned no valid JSON
17:45:53 – (FOUT) greenchoice (aangepaste integratie) - bericht kwam voor het eerst om 14:44:23 en verschijnt 4 keer

Could not update meter values: request returned no valid JSON
17:45:53 – (FOUT) greenchoice (aangepaste integratie) - bericht kwam voor het eerst om 14:44:23 en verschijnt 4 keer

Sensor sensor.meterstanden_gas_consumption has device class gas, state class total and unit m³ thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Sensor sensor.meterstanden_gas_price has device class monetary, state class total and unit EUR/m³ thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
13:44:21 – (WAARSCHUWING) Sensor - bericht kwam voor het eerst om 13:44:20 en verschijnt 2 keer

```

**Comment by Drippydh** [comment]
Someone got a solution for this? I got the same issue:
Could not update contract values: request returned no valid JSON

**Comment by Flightkick** [comment]
With some additional debug logging I was able to find out that the requests from the `update()` functions are redirected to `https://sso.greenchoice.nl/Account/Login`. Which is why the error is thrown that the response isn't valid JSON, it's HTML.

When I manually ran the script:
```python
api = GreenchoiceApiData("USERNAME", "PASSWORD")
results = api.update()
print(results)
```

The request completed as expected and valid JSON data is returned.

-----

My hypothesis is that the error is the result of an expired session and that the API doesn't return a HTTP 403 anymore when a session is expired but redirects with a HTTP 302 instead. Since this is not caught as expired session behavior by the script it fails to handle it here:
https://github.com/barisdemirdelen/homeassistant-greenchoice/blob/00eff0f80a36f7cc02de5b50c0c5101abb0f2064/custom_components/greenchoice/api.py#L113-L116

The session cookies are encrypted, don't use an open standard like JWT and don't have a matching cookie expiration time. This makes it slightly more difficult to debug as the expiration time isn't known to me. In other words, I need to wait for some unspecified amount of time for my session to expire now before I can debug this further and propose a potential fix.

**Comment by Flightkick** [comment]
Confirmed that this is indeed what's happening. The session expires and the subsequent calls to `https://mijn.greenchoice.nl/microbus/request` result in a 302 redirect to `https://sso.greenchoice.nl/connect/authorize` with the following response bodies:

`OpnamesOphalen` results in:
```json
{
  "success": false,
  "messages": [
    {
      "type": 2,
      "code": "OPNAMESOPHALEN_GEEN_RECHTEN",
      "message": "Je hebt onvoldoende rechten om opnames op te halen"
    }
  ]
}
```

`GetTariefOvereenkomst` results in:
```json
{
  "stroom": null,
  "gas": null,
  "totaleJaarlijksteKostenIncBtw": 0.0
}
```

After the redirect, the client receives a HTTP 200 HTML content page. As mentioned before, this is not currently handled.
I think the most elegant remaining solution would be to check if the response history contains a `302` to `https://sso.greenchoice.nl/connect/authorize` and re-authenticate if that is the case.

I'll try to submit a patch tomorrow.

**Comment by cpvbruno** [comment]
@barisdemirdelen could you check this PR?
